apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: storyaudio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: story-audio-backend:latest
          imagePullPolicy: Never  # Important for local images
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: tts-keys
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: storyaudio
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
